
Now we can get started by creating a module and a widget with console generation commands. If you haven’t used Drupal Console before, it gives you a bunch of scaffolding commands to generate basic plugins and components, which saves a lot of time when you’re getting up and running
(although sometimes what it generates isn’t ideal). You can see all of these commands by running `drupal list generate`:

....
$ drupal list generate
Drupal Console Launcher version 1.9.4
Drupal Console version 1.9.4

Available commands for the "generate" namespace:
  generate:ajax:command (gac)                 Generate & Register a custom ajax command
  generate:authentication:provider (gap)      Generate an Authentication Provider
  generate:block:type (gbt)                   Generate a block content type
  generate:breakpoint (gb)                    Generate breakpoint
  generate:cache:context (gcc)                Generate a cache context
  ...
....

This will give you a long list of all of the available generate commands. The two we’re interested in right now are `generate:module` and `generate:plugin:fieldwidget`.

To get started, let’s generate a module to add our Widget to:

[source,text]
----
> ddev drupal generate:module

 // Welcome to the Drupal module generator

 Enter the new module name:
 > Example widget

 Enter the module machine name [my_module]:
 >

 Enter the module Path [modules/custom]:
 >

 Enter module description [My Awesome Module]:
 > A module for my example widget

 Enter package name [Custom]:
 >

 Enter Drupal Core version [8.x]:
 >

 Do you want to generate a .module file? (yes/no) [yes]:
 > yes

 Define module as feature (yes/no) [no]:
 > no

 Do you want to add a composer.json file to your module? (yes/no) [yes]:
 > no

 Would you like to add module dependencies? (yes/no) [no]:
 > yes

 Module dependencies separated by commas (i.e. context, panels):
 > text

 Do you want to generate a unit test class? (yes/no) [yes]:
 > no

 Do you want to generate a themeable template? (yes/no) [yes]:
 > no

 Do you want proceed with the operation? (yes/no) [yes]:
 > yes
----

This will generate a basic module structure like this:

[source,text]
----
web/modules/custom/
└── example_widget
     ├── example_widget.info.yml
     └── example_widget.module
----

We can then generate our base widget:

[source,text]
----
web/modules/custom/
└── example_widget
    ├── example_widget.info.yml
    └── example_widget.module
    ├── example_widget.schema.yml
    └── src
        └── Plugin
            └── Field
                └── FieldWidget
                    └── ExampleWidgetFieldWidget.php <1>
----
<1> The structure of these directories and the associated namespace is important for this to work.

This creates both a widget plugin class, and a `schema.yml` file. Let’s take a look at what’s in these.

[source,php]
----
<?php

namespace Drupal\example_widget\Plugin\Field\FieldWidget;

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Plugin implementation of the 'example_widget_field_widget' widget.
 *
 * @FieldWidget(
 *   id = "example_widget_field_widget",
 *   module = "my_module",
 *   label = @Translation("Example widget field widget"),
 *   field_types = {
 *     "string"
 *   }
 * )
 */
class ExampleWidgetFieldWidget extends WidgetBase {

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    return [
      'size' => 60,
      'placeholder' => '',
    ] + parent::defaultSettings();
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm(array $form, FormStateInterface $form_state) {
    $elements = [];

    $elements['size'] = [
      '#type' => 'number',
      '#title' => t('Size of textfield'),
      '#default_value' => $this->getSetting('size'),
      '#required' => TRUE,
      '#min' => 1,
    ];
    $elements['placeholder'] = [
      '#type' => 'textfield',
      '#title' => t('Placeholder'),
      '#default_value' => $this->getSetting('placeholder'),
      '#description' => t('Text that will be shown inside the field until a value is entered. This hint is usually a sample value or a brief description of the expected format.'),
    ];

    return $elements;
  }

  /**
   * {@inheritdoc}
   */
  public function settingsSummary() {
    $summary = [];

    $summary[] = t('Textfield size: @size', ['@size' => $this->getSetting('size')]);
    if (!empty($this->getSetting('placeholder'))) {
      $summary[] = t('Placeholder: @placeholder', ['@placeholder' => $this->getSetting('placeholder')]);
    }

    return $summary;
  }

  /**
   * {@inheritdoc}
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state) {
    $element['value'] = $element + [
      '#type' => 'textfield',
      '#default_value' => isset($items[$delta]->value) ? $items[$delta]->value : NULL,
      '#size' => $this->getSetting('size'),
      '#placeholder' => $this->getSetting('placeholder'),
      '#maxlength' => $this->getFieldSetting('max_length'),
    ];

    return $element;
  }

}
----
